#|
    Draw the tree illustrating the process generated by the 
    count-change procedure of Section 1.2.2 in making change
    for 11 cents. 

                                                                                   (count-change 11)

                                                     (cc 11 5)                                                                        (cc 11 4)
            
                              (cc 11 4)                                       (cc 11 3)                                 (cc 11 3)                (cc 11 2)                     
    
                  (cc 11 3)                (cc 11 2)                   (cc 11 2)      (cc 11 1)                  (cc 11 2)    (cc 11 1)    (cc 11 1)      (cc 11 0)
    
            (cc 11 2)    (cc 11 1)     (cc 11 1)(cc 11 0)           (cc 11 1)(cc 11 0)                        (cc 11 1)(cc 11 0)
    
        (cc 11 1)(cc 11 0)
    
    
    
    What are the orders of growth of the space
    and number of steps used by this process as the amount to
    be changed increases? 

        The space, or number of deferred operations, of the function count-change 
        grows in proportion to the kinds-of-change variable in the nested function (cc amount kinds-of-change).

        The time, or number of primitive steps, grows in proportion to this variable.

        Time and Space orders of growth are both linear or theta(n)  
|#