#|
    EXERICISE 1.9
        Each of the following two procedures defines a method for adding two 
        positive inteders in terms of the procedures inc, which increments its
        arguments by 1, and dec, which decrements its arguments by 1.
        
        1.
            (define (+ a b)
                (if (= a 0) b (inc (+ (dec a) b))))
        
        2.
            (define (+ a b)
                (if (= a 0) b (+ (dec a) (inc b))))

        Using the substitution model, illustrate the process generated by each
        procedure in evaluating (+ 4 5). Are these processes iterative or recursive?


        1:
            (if (= 4 0) 5 (inc (+ (dec 4) 5)))
            (inc (+ (dec 4) 5))
            (inc (if (= 3 0) 5 (inc (+ (dec 3) 5))))
            (inc (inc (+ (dec 3) 5)))
            (inc (inc (if (= 2 0) 5 (inc (+ (dec 2) 5)))))
            (inc (inc (inc (+ (dec 2) 5))))
            (inc (inc (inc (if (= 1 0) 5 (inc (+ (dec 1) 5))))))
            (inc (inc (inc (inc (+ (dec 1) 5)))))
            (inc (inc (inc (inc (if (= 0 0) 5 (inc (+ (dec 0) 5)))))))
            (inc (inc (inc (inc 5))))
            (inc (inc (inc 6)))
            (inc (inc 7))
            (inc 8)
            9

            This is a recursive process. The process expands as a chain of deferred 
            operations builds up, once the base case of (= a 0) is hit the process is
            allowed to contract as the deferred operations are performed.
        
        2:
            (if (= 4 0) 5 (+ (dec 4) (inc 5)))
            (+ 3 6)
            (if (= 3 0) 6 (+ (dec 3) (inc 6)))
            (+ 2 7)
            (if (= 2 0) 7 (+ (dec 2) (inc 7)))
            (+ 1 8)
            (if (= 1 0) 8 (+ (dec 1) (inc 8)))
            (+ 0 9)
            (if (= 0 0) 9 (+ (dec 0) (inc 9)))
            9
       
            This is an iterative process. The process has a fixed number of state variables
            with a rule that describes how they update from state to state. When (= a 0)
            we are given b which at this point has been updated to 9, the solution to the problem.
|#