/*
    Each of the following two functions defines a method for adding
    two positive integers in terms of the functions inc, which increments
    its argument by 1, and dec, which decrements its argument by 1.
*/

function plus(a, b){
    return a === 0 ? b :
    inc(plus(dec(a), b))
}

function plus(a, b) {
    return a === 0 ? b :
    plus(dec(a), inc(b))
}

/*
    Using the substitution model, illustrate the process generated by each
    function in evaluating (4, 5)

    Are these processes iterative or recursive?
*/

